site_name: Employee Handbook 
theme:
  features:
    # - navigation.expand
    - navigation.sections
    - navigation.footer
  font:
    text: Outfit
  name: material
  palette:
    primary: light blue
copyright: Copyright &copy; 2024 Skybase Innovations Pvt. Ltd.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/skybase.innovations
nav:
- Introduction : index.md
- Core:
  - Employment:
    - Welcome : welcome.md
    - About Your Employment : about.md
    - Calendar and Leave Policy : leave.md
    - Payments and Benefits : payment.md
    - Accidents, Misconduct and Disputes : accident.md
# - Conventions : conventions.md
- Development:
  - Conventions:
    - Git Conventions : git-conventions.md
    - Version Conventions : conventions.md
- Tutorials:
  - Sign in with Apple | Flutter:
    - Introduction: signin-with-apple/README.md
    - Configure Apple Developer Account: signin-with-apple/step-1.md
    - Set up Apple Service ID: signin-with-apple/step-2-set-up-apple-service-id.md
    - Configure in Xcode: signin-with-apple/step-3-configure-in-xcode.md
    - Implement in App: signin-with-apple/step-4-implement-apple-sign-in-in-app-using-flutter.md